name: daily_productivity
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  badges: ^2.0.1
  bloc: ^7.2.0
  fl_chart: ^0.40.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_localizations:
    sdk: flutter
  font_awesome: ^5.10.1
  font_awesome_flutter: ^9.1.0
  google_fonts: ^2.1.0
  intl: ^0.17.0
  sleek_circular_slider: ^2.0.1
  table_calendar: ^3.0.2
  url_launcher: ^6.0.12

dev_dependencies:
  bloc_test: ^8.2.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
